name: dart_samples
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  path: ^1.7.0
  uuid: ^3.0.4
  intl: ^0.17.0
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
